In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import requests
import pickle
import io

# Import the preprocessed data
X_preprocessed_url = "https://static.bc-edx.com/ai/ail-v-1-0/m19/lesson_2/datasets/pickles/preprocessed_fungi.pkl"
y_url = "https://static.bc-edx.com/ai/ail-v-1-0/m19/lesson_2/datasets/pickles/fungi_y.pkl"

X = pickle.load(io.BytesIO(requests.get(X_preprocessed_url).content))
y = pickle.load(io.BytesIO(requests.get(y_url).content))

print(X[0])
print(y.head())


[[[0.5568628  0.5647059  0.56078434]
  [0.5568628  0.5647059  0.56078434]
  [0.5568628  0.5647059  0.56078434]
  ...
  [0.53333336 0.54901963 0.54509807]
  [0.5372549  0.5529412  0.54901963]
  [0.5372549  0.5529412  0.54901963]]

 [[0.54901963 0.5568628  0.5529412 ]
  [0.54901963 0.5568628  0.5529412 ]
  [0.5529412  0.56078434 0.5568628 ]
  ...
  [0.53333336 0.54901963 0.54509807]
  [0.5372549  0.5529412  0.54901963]
  [0.5372549  0.5529412  0.54901963]]

 [[0.53333336 0.5411765  0.5372549 ]
  [0.5411765  0.54901963 0.54509807]
  [0.54901963 0.5568628  0.5529412 ]
  ...
  [0.5254902  0.5411765  0.5372549 ]
  [0.5294118  0.54509807 0.5411765 ]
  [0.5294118  0.54509807 0.5411765 ]]

 ...

 [[0.5529412  0.53333336 0.4509804 ]
  [0.5529412  0.53333336 0.4509804 ]
  [0.54901963 0.5254902  0.44705883]
  ...
  [0.54509807 0.5529412  0.5568628 ]
  [0.54509807 0.5529412  0.56078434]
  [0.54509807 0.5529412  0.56078434]]

 [[0.54901963 0.5254902  0.44705883]
  [0.54901963 0.5254902  0.44705883]


In [3]:
# Label encode the y data
y_encoder = LabelEncoder().fit(y)
y = y_encoder.transform(y)

# Convert values to numpy arrays
X = np.array(X)

# Split the training dataset into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define a CNN model; make sure to use the correct values for input shape!
# HINT: Check the preprocessing activity to see the dimensions we used.


# Compile the model


# Train the model



Epoch 1/10
7/7 [==============================] - 15s 2s/step - loss: 17.9034 - accuracy: 0.5300 - val_loss: 2.5800 - val_accuracy: 0.7000
Epoch 2/10
7/7 [==============================] - 13s 2s/step - loss: 5.1542 - accuracy: 0.6350 - val_loss: 1.3014 - val_accuracy: 0.7000
Epoch 3/10
7/7 [==============================] - 13s 2s/step - loss: 1.5989 - accuracy: 0.4450 - val_loss: 1.0612 - val_accuracy: 0.3000
Epoch 4/10
7/7 [==============================] - 12s 2s/step - loss: 0.7294 - accuracy: 0.5350 - val_loss: 0.6102 - val_accuracy: 0.7000
Epoch 5/10
7/7 [==============================] - 12s 2s/step - loss: 0.7379 - accuracy: 0.4850 - val_loss: 0.6166 - val_accuracy: 0.7200
Epoch 6/10
7/7 [==============================] - 13s 2s/step - loss: 0.6759 - accuracy: 0.5800 - val_loss: 0.5772 - val_accuracy: 0.7200
Epoch 7/10
7/7 [==============================] - 13s 2s/step - loss: 0.6483 - accuracy: 0.6450 - val_loss: 0.5752 - val_accuracy: 0.7200
Epoch 8/10
7/7 [=================